import type { Database } from "@pakcommerce/integrations/supabase";
import type {
  InventoryState,
  Product,
  ProductListItem,
  ProductOption,
  ProductVariant,
  ProductVariantOptionValue,
} from "@pakcommerce/shared";

/**
 * Translates between the database and the shared contract.
 *
 * They are shaped differently on purpose. The contract is nested and camelCase
 * because that is convenient for callers; the tables are flat and snake_case
 * because that is what indexes and constraints work on. Money is
 * `{ amountMinor, currency }` in the contract and two columns in storage.
 *
 * All of that translation lives here, in pure functions, so it can be tested
 * without a database and so no handler is tempted to do it inline.
 */

type ProductRow = Database["public"]["Tables"]["products"]["Row"];
type VariantRow = Database["public"]["Tables"]["product_variants"]["Row"];

export function toProductVariant(row: VariantRow): ProductVariant {
  return {
    id: row.id,
    productId: row.product_id,
    title: row.title,
    sku: row.sku,
    barcode: row.barcode,
    status: row.status,
    price: {
      amountMinor: row.price_amount_minor,
      currency: row.price_currency as "PKR",
    },
    compareAtPrice:
      row.compare_at_price_amount_minor === null
        ? null
        : {
            amountMinor: row.compare_at_price_amount_minor,
            currency: (row.compare_at_price_currency ?? "PKR") as "PKR",
          },
    optionValues: (row.option_values ?? []) as unknown as ProductVariantOptionValue[],
    inventory: {
      trackInventory: row.track_inventory,
      quantityOnHand: row.quantity_on_hand,
      lowStockThreshold: row.low_stock_threshold,
      // Generated by the database, never written by the application.
      state: row.inventory_state as InventoryState,
    },
    position: row.position,
    // No product_images table yet, so a variant cannot reference one.
    imageId: null,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

export function toProduct(row: ProductRow, variantRows: VariantRow[]): Product {
  return {
    id: row.id,
    sellerId: row.seller_id,
    workspaceId: row.workspace_id,
    title: row.title,
    slug: row.slug,
    description: row.description,
    status: row.status,
    tags: row.tags,
    categoryIds: row.category_ids,
    options: (row.options ?? []) as unknown as ProductOption[],
    variants: variantRows
      .slice()
      .sort((a, b) => a.position - b.position)
      .map(toProductVariant),
    // Empty rather than absent: `images` is a required key in the contract and an
    // empty array satisfies it. The product_images table is a later task, so
    // there is nothing to map yet - and pretending otherwise would be worse.
    images: [],
    searchText: row.search_text,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    archivedAt: row.archived_at,
  };
}

/**
 * Rolls variant stock up to one product-level state for list views.
 *
 * The contract defines `inventoryState` on a list item but not how to derive it
 * from several variants, so the rule is chosen here and stated plainly:
 * **a product is as available as its most available variant.** A seller scanning
 * a list wants to know "can I sell this at all", and one in-stock size means yes.
 *
 * `untracked` only wins when nothing is tracked, otherwise it would mask a real
 * out-of-stock.
 *
 * Takes the distinct states rather than the variant rows, because that is what
 * `product_list_view` aggregates - keeping the rule in TypeScript instead of
 * duplicating it in SQL.
 */
export function rollUpInventoryState(states: readonly string[]): InventoryState {
  if (states.includes("in_stock")) return "in_stock";
  if (states.includes("low_stock")) return "low_stock";
  if (states.includes("out_of_stock")) return "out_of_stock";

  return "untracked";
}

/** A row of `product_list_view` - products plus rolled-up variant facts. */
export interface ProductListRow {
  id: string;
  workspace_id: string;
  seller_id: string;
  title: string;
  slug: string;
  status: ProductRow["status"];
  tags: string[];
  category_ids: string[];
  created_at: string;
  updated_at: string;
  archived_at: string | null;
  variant_count: number;
  min_price_amount_minor: number;
  max_price_amount_minor: number;
  price_currency: string;
  variant_states: string[];
}

export function toProductListItem(row: ProductListRow): ProductListItem {
  const currency = row.price_currency as "PKR";

  return {
    id: row.id,
    sellerId: row.seller_id,
    workspaceId: row.workspace_id,
    title: row.title,
    slug: row.slug,
    status: row.status,
    tags: row.tags,
    categoryIds: row.category_ids,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    archivedAt: row.archived_at,
    // Same reason as `images` above: no product_images table yet.
    primaryImage: null,
    // Postgres counts as bigint, which arrives as a string over PostgREST.
    variantCount: Number(row.variant_count),
    priceRange: {
      min: { amountMinor: Number(row.min_price_amount_minor), currency },
      max: { amountMinor: Number(row.max_price_amount_minor), currency },
    },
    inventoryState: rollUpInventoryState(row.variant_states),
  };
}
